// Code generated by protoc-gen-go. DO NOT EDIT.
// source: srv1.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Msg0 struct {
	Id1                  int64    `protobuf:"varint,1,opt,name=id1,proto3" json:"id1,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Msg0) Reset()         { *m = Msg0{} }
func (m *Msg0) String() string { return proto.CompactTextString(m) }
func (*Msg0) ProtoMessage()    {}
func (*Msg0) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6330b32150a8abd, []int{0}
}

func (m *Msg0) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg0.Unmarshal(m, b)
}
func (m *Msg0) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg0.Marshal(b, m, deterministic)
}
func (m *Msg0) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg0.Merge(m, src)
}
func (m *Msg0) XXX_Size() int {
	return xxx_messageInfo_Msg0.Size(m)
}
func (m *Msg0) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg0.DiscardUnknown(m)
}

var xxx_messageInfo_Msg0 proto.InternalMessageInfo

func (m *Msg0) GetId1() int64 {
	if m != nil {
		return m.Id1
	}
	return 0
}

type Msg1 struct {
	Id1                  int64    `protobuf:"varint,1,opt,name=id1,proto3" json:"id1,omitempty"`
	Id2                  int64    `protobuf:"varint,2,opt,name=id2,proto3" json:"id2,omitempty"`
	Msg1                 string   `protobuf:"bytes,3,opt,name=msg1,proto3" json:"msg1,omitempty"`
	Msg2                 string   `protobuf:"bytes,4,opt,name=msg2,proto3" json:"msg2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Msg1) Reset()         { *m = Msg1{} }
func (m *Msg1) String() string { return proto.CompactTextString(m) }
func (*Msg1) ProtoMessage()    {}
func (*Msg1) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6330b32150a8abd, []int{1}
}

func (m *Msg1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg1.Unmarshal(m, b)
}
func (m *Msg1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg1.Marshal(b, m, deterministic)
}
func (m *Msg1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg1.Merge(m, src)
}
func (m *Msg1) XXX_Size() int {
	return xxx_messageInfo_Msg1.Size(m)
}
func (m *Msg1) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg1.DiscardUnknown(m)
}

var xxx_messageInfo_Msg1 proto.InternalMessageInfo

func (m *Msg1) GetId1() int64 {
	if m != nil {
		return m.Id1
	}
	return 0
}

func (m *Msg1) GetId2() int64 {
	if m != nil {
		return m.Id2
	}
	return 0
}

func (m *Msg1) GetMsg1() string {
	if m != nil {
		return m.Msg1
	}
	return ""
}

func (m *Msg1) GetMsg2() string {
	if m != nil {
		return m.Msg2
	}
	return ""
}

type Msg2 struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Msg2) Reset()         { *m = Msg2{} }
func (m *Msg2) String() string { return proto.CompactTextString(m) }
func (*Msg2) ProtoMessage()    {}
func (*Msg2) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6330b32150a8abd, []int{2}
}

func (m *Msg2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg2.Unmarshal(m, b)
}
func (m *Msg2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg2.Marshal(b, m, deterministic)
}
func (m *Msg2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg2.Merge(m, src)
}
func (m *Msg2) XXX_Size() int {
	return xxx_messageInfo_Msg2.Size(m)
}
func (m *Msg2) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg2.DiscardUnknown(m)
}

var xxx_messageInfo_Msg2 proto.InternalMessageInfo

func (m *Msg2) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Msg2) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type Msg3 struct {
	Id1                  int64    `protobuf:"varint,1,opt,name=id1,proto3" json:"id1,omitempty"`
	Msg1                 *Msg1    `protobuf:"bytes,2,opt,name=msg1,proto3" json:"msg1,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Msg3) Reset()         { *m = Msg3{} }
func (m *Msg3) String() string { return proto.CompactTextString(m) }
func (*Msg3) ProtoMessage()    {}
func (*Msg3) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6330b32150a8abd, []int{3}
}

func (m *Msg3) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg3.Unmarshal(m, b)
}
func (m *Msg3) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg3.Marshal(b, m, deterministic)
}
func (m *Msg3) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg3.Merge(m, src)
}
func (m *Msg3) XXX_Size() int {
	return xxx_messageInfo_Msg3.Size(m)
}
func (m *Msg3) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg3.DiscardUnknown(m)
}

var xxx_messageInfo_Msg3 proto.InternalMessageInfo

func (m *Msg3) GetId1() int64 {
	if m != nil {
		return m.Id1
	}
	return 0
}

func (m *Msg3) GetMsg1() *Msg1 {
	if m != nil {
		return m.Msg1
	}
	return nil
}

type Msg4 struct {
	Id1                  int64    `protobuf:"varint,1,opt,name=id1,proto3" json:"id1,omitempty"`
	Msg3                 *Msg3    `protobuf:"bytes,2,opt,name=msg3,proto3" json:"msg3,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Msg4) Reset()         { *m = Msg4{} }
func (m *Msg4) String() string { return proto.CompactTextString(m) }
func (*Msg4) ProtoMessage()    {}
func (*Msg4) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6330b32150a8abd, []int{4}
}

func (m *Msg4) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg4.Unmarshal(m, b)
}
func (m *Msg4) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg4.Marshal(b, m, deterministic)
}
func (m *Msg4) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg4.Merge(m, src)
}
func (m *Msg4) XXX_Size() int {
	return xxx_messageInfo_Msg4.Size(m)
}
func (m *Msg4) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg4.DiscardUnknown(m)
}

var xxx_messageInfo_Msg4 proto.InternalMessageInfo

func (m *Msg4) GetId1() int64 {
	if m != nil {
		return m.Id1
	}
	return 0
}

func (m *Msg4) GetMsg3() *Msg3 {
	if m != nil {
		return m.Msg3
	}
	return nil
}

type Msg5 struct {
	Id1                  int64    `protobuf:"varint,1,opt,name=id1,proto3" json:"id1,omitempty"`
	Names                []string `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Msg5) Reset()         { *m = Msg5{} }
func (m *Msg5) String() string { return proto.CompactTextString(m) }
func (*Msg5) ProtoMessage()    {}
func (*Msg5) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6330b32150a8abd, []int{5}
}

func (m *Msg5) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg5.Unmarshal(m, b)
}
func (m *Msg5) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg5.Marshal(b, m, deterministic)
}
func (m *Msg5) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg5.Merge(m, src)
}
func (m *Msg5) XXX_Size() int {
	return xxx_messageInfo_Msg5.Size(m)
}
func (m *Msg5) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg5.DiscardUnknown(m)
}

var xxx_messageInfo_Msg5 proto.InternalMessageInfo

func (m *Msg5) GetId1() int64 {
	if m != nil {
		return m.Id1
	}
	return 0
}

func (m *Msg5) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

func init() {
	proto.RegisterType((*Msg0)(nil), "pb.Msg0")
	proto.RegisterType((*Msg1)(nil), "pb.Msg1")
	proto.RegisterType((*Msg2)(nil), "pb.Msg2")
	proto.RegisterType((*Msg3)(nil), "pb.Msg3")
	proto.RegisterType((*Msg4)(nil), "pb.Msg4")
	proto.RegisterType((*Msg5)(nil), "pb.Msg5")
}

func init() { proto.RegisterFile("srv1.proto", fileDescriptor_f6330b32150a8abd) }

var fileDescriptor_f6330b32150a8abd = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0x69, 0x5a, 0xd7, 0xdd, 0x11, 0x44, 0x82, 0x87, 0x20, 0x0a, 0x25, 0xa7, 0x9e, 0xc2,
	0x66, 0xd2, 0x7a, 0xf1, 0xa6, 0x5e, 0xbd, 0xc4, 0x9b, 0xb7, 0xad, 0x2d, 0xa5, 0xb0, 0xb5, 0xa5,
	0x91, 0xfd, 0xa3, 0xfe, 0x21, 0xc9, 0xb4, 0xbb, 0x50, 0x37, 0xde, 0x5e, 0xde, 0x7c, 0xef, 0x4d,
	0x08, 0x01, 0x70, 0xe3, 0x41, 0xab, 0x61, 0xec, 0xbf, 0x7b, 0xce, 0x86, 0x52, 0x0a, 0x48, 0xde,
	0x5c, 0xb3, 0xe5, 0x37, 0x10, 0xb7, 0x95, 0x16, 0x51, 0x1a, 0x65, 0xb1, 0xf5, 0x52, 0x5a, 0x9a,
	0xe8, 0xf3, 0xc9, 0xe4, 0xa0, 0x60, 0x47, 0x07, 0x39, 0x87, 0xa4, 0x73, 0x8d, 0x16, 0x71, 0x1a,
	0x65, 0x1b, 0x4b, 0x7a, 0xf6, 0x50, 0x24, 0x27, 0x0f, 0x65, 0x46, 0x9d, 0xc8, 0xaf, 0x81, 0xb5,
	0xd5, 0x5c, 0xc9, 0xda, 0xca, 0x37, 0x76, 0xae, 0xa1, 0xc6, 0x8d, 0xf5, 0x52, 0x3e, 0x12, 0x69,
	0x02, 0xdb, 0xef, 0xe7, 0x5d, 0x1e, 0xbe, 0xc2, 0xb5, 0x1a, 0x4a, 0xe5, 0xef, 0x39, 0x6d, 0x9d,
	0x73, 0xf9, 0xbf, 0x39, 0xf3, 0x27, 0x67, 0x28, 0x67, 0xa4, 0xa2, 0x5c, 0x11, 0xc8, 0xdd, 0xc2,
	0xc5, 0xd7, 0xae, 0xab, 0x9d, 0x60, 0x69, 0x9c, 0x6d, 0xec, 0x74, 0xc0, 0x9f, 0x08, 0xd6, 0xef,
	0xf5, 0x78, 0x68, 0x3f, 0x6b, 0xcd, 0x1f, 0xe0, 0xf2, 0xb5, 0x7f, 0xd9, 0xed, 0xf7, 0x9a, 0x1f,
	0x7b, 0xb7, 0x77, 0x27, 0xc5, 0x53, 0x80, 0x69, 0x4c, 0xef, 0x79, 0x4e, 0xe8, 0x05, 0x81, 0x01,
	0x02, 0x17, 0x84, 0x09, 0x10, 0x66, 0x41, 0xe4, 0x01, 0x22, 0x5f, 0x10, 0x45, 0x80, 0x28, 0x9e,
	0x57, 0x1f, 0x89, 0x7a, 0x1a, 0xca, 0x72, 0x45, 0x1f, 0xc4, 0xfc, 0x06, 0x00, 0x00, 0xff, 0xff,
	0xb9, 0xc3, 0x77, 0x18, 0x2e, 0x02, 0x00, 0x00,
}
