// Code generated by protoc-gen-go. DO NOT EDIT.
// source: srv2.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginMessage struct {
	UserName             string   `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	PassHash             string   `protobuf:"bytes,2,opt,name=PassHash,proto3" json:"PassHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginMessage) Reset()         { *m = LoginMessage{} }
func (m *LoginMessage) String() string { return proto.CompactTextString(m) }
func (*LoginMessage) ProtoMessage()    {}
func (*LoginMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_f44b02b9441874c1, []int{0}
}

func (m *LoginMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginMessage.Unmarshal(m, b)
}
func (m *LoginMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginMessage.Marshal(b, m, deterministic)
}
func (m *LoginMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginMessage.Merge(m, src)
}
func (m *LoginMessage) XXX_Size() int {
	return xxx_messageInfo_LoginMessage.Size(m)
}
func (m *LoginMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginMessage.DiscardUnknown(m)
}

var xxx_messageInfo_LoginMessage proto.InternalMessageInfo

func (m *LoginMessage) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *LoginMessage) GetPassHash() string {
	if m != nil {
		return m.PassHash
	}
	return ""
}

type UserInfoMessage struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	FistName             string   `protobuf:"bytes,2,opt,name=FistName,proto3" json:"FistName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=LastName,proto3" json:"LastName,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=Email,proto3" json:"Email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoMessage) Reset()         { *m = UserInfoMessage{} }
func (m *UserInfoMessage) String() string { return proto.CompactTextString(m) }
func (*UserInfoMessage) ProtoMessage()    {}
func (*UserInfoMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_f44b02b9441874c1, []int{1}
}

func (m *UserInfoMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoMessage.Unmarshal(m, b)
}
func (m *UserInfoMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoMessage.Marshal(b, m, deterministic)
}
func (m *UserInfoMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoMessage.Merge(m, src)
}
func (m *UserInfoMessage) XXX_Size() int {
	return xxx_messageInfo_UserInfoMessage.Size(m)
}
func (m *UserInfoMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoMessage.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoMessage proto.InternalMessageInfo

func (m *UserInfoMessage) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserInfoMessage) GetFistName() string {
	if m != nil {
		return m.FistName
	}
	return ""
}

func (m *UserInfoMessage) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UserInfoMessage) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type LoginResultMessage struct {
	UserInfo             *UserInfoMessage `protobuf:"bytes,1,opt,name=UserInfo,proto3" json:"UserInfo,omitempty"`
	Result               bool             `protobuf:"varint,2,opt,name=Result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *LoginResultMessage) Reset()         { *m = LoginResultMessage{} }
func (m *LoginResultMessage) String() string { return proto.CompactTextString(m) }
func (*LoginResultMessage) ProtoMessage()    {}
func (*LoginResultMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_f44b02b9441874c1, []int{2}
}

func (m *LoginResultMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResultMessage.Unmarshal(m, b)
}
func (m *LoginResultMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResultMessage.Marshal(b, m, deterministic)
}
func (m *LoginResultMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResultMessage.Merge(m, src)
}
func (m *LoginResultMessage) XXX_Size() int {
	return xxx_messageInfo_LoginResultMessage.Size(m)
}
func (m *LoginResultMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResultMessage.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResultMessage proto.InternalMessageInfo

func (m *LoginResultMessage) GetUserInfo() *UserInfoMessage {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

func (m *LoginResultMessage) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func init() {
	proto.RegisterType((*LoginMessage)(nil), "pb.LoginMessage")
	proto.RegisterType((*UserInfoMessage)(nil), "pb.UserInfoMessage")
	proto.RegisterType((*LoginResultMessage)(nil), "pb.LoginResultMessage")
}

func init() { proto.RegisterFile("srv2.proto", fileDescriptor_f44b02b9441874c1) }

var fileDescriptor_f44b02b9441874c1 = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0x59, 0xb7, 0x95, 0xfa, 0x14, 0x95, 0x28, 0xa3, 0xec, 0x24, 0x3d, 0x79, 0xaa, 0x18,
	0x8f, 0xe2, 0x45, 0x70, 0x58, 0x98, 0x22, 0x11, 0x2f, 0x82, 0x87, 0xc4, 0xc5, 0x19, 0xd8, 0x96,
	0x90, 0x57, 0xfb, 0xf7, 0x4b, 0x5e, 0x9a, 0xa2, 0x3b, 0x7e, 0xf9, 0xe5, 0x7d, 0xef, 0xc7, 0x03,
	0x40, 0xdf, 0xf1, 0xda, 0x79, 0xdb, 0x5a, 0x96, 0x39, 0x55, 0x2d, 0xe0, 0x68, 0x69, 0xd7, 0x66,
	0xf7, 0xa4, 0x11, 0xe5, 0x5a, 0xb3, 0x39, 0x14, 0x6f, 0xa8, 0xfd, 0xb3, 0xdc, 0xea, 0x72, 0x74,
	0x31, 0xba, 0x3c, 0x10, 0x43, 0x0e, 0xec, 0x45, 0x22, 0x3e, 0x4a, 0xfc, 0x2e, 0xb3, 0xc8, 0x52,
	0xae, 0x2c, 0x9c, 0x84, 0x7f, 0xcd, 0xee, 0xcb, 0xa6, 0xaa, 0x63, 0xc8, 0x9a, 0x15, 0x95, 0x8c,
	0x45, 0xd6, 0xac, 0xc2, 0xf8, 0xc2, 0x60, 0x4b, 0xd5, 0xfd, 0x78, 0xca, 0x81, 0x2d, 0x65, 0xcf,
	0xc6, 0x91, 0xa5, 0xcc, 0xce, 0x61, 0xfa, 0xb0, 0x95, 0x66, 0x53, 0x4e, 0x08, 0xc4, 0x50, 0x7d,
	0x00, 0x23, 0x71, 0xa1, 0xf1, 0x67, 0xd3, 0xa6, 0x9d, 0x57, 0x51, 0x3f, 0x68, 0xd0, 0xe6, 0x43,
	0x7e, 0x56, 0x3b, 0x55, 0xef, 0xa9, 0x89, 0xe1, 0x13, 0x9b, 0x41, 0x1e, 0x1b, 0x48, 0xa9, 0x10,
	0x7d, 0xe2, 0x77, 0x50, 0xbc, 0x6a, 0xdf, 0x99, 0x4f, 0xcd, 0xd9, 0x35, 0x4c, 0x69, 0x15, 0x3b,
	0x0d, 0x5d, 0x7f, 0xcf, 0x35, 0x9f, 0x0d, 0x2f, 0xff, 0x3c, 0xee, 0xf3, 0xf7, 0x49, 0x7d, 0xeb,
	0x94, 0xca, 0xe9, 0xd2, 0x37, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x97, 0x81, 0xd3, 0x43, 0x77,
	0x01, 0x00, 0x00,
}
